### ISSUE TITLE
Phase 1 wrap-up

### ISSUE THREAD

**Issue by stmcgovern** [NexGenAnalytics/WorkVisualizer#69]
- After the analysis is run, make the displaying of the result, i.e. a rank of interest to look at,  obvious to the user.

**Comment by cwschilly** [comment]
Adding notes for work that should be done in Phase 2:
- Allow user to upload multiple runs and easily access and compare them in a single WV "session"
- General optimizations and speed-up (adaptive zooming on Events Plot, for example)
- Improved analysis and more robust slicing techniques
- Collection of GPU data
